version: '3.2'
services:
  database:
    container_name: database
    image: mysql:8.0.16
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  core:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root
    depends_on:
      - database
