version: '3.3'
services:
  database:
    container_name: database
    image: mysql:8.0.16
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  core:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure:3
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root
      - START_DELAY=20000
    depends_on:
      - database
